name: CI - Website

on:
  push:
    branches:
      - main
  pull_request: {}

env:
  NODE_VERSION: '20.x'

concurrency:
  group: ci-website-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  conditional-skip:
    runs-on: ubuntu-latest 
    name: Get files changed and conditionally skip CI
    outputs:
      trigger-ci: ${{ steps.read-files.outputs.trigger-ci }}
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: 0  
      - name: Get changed files
        id: read-files
        run: ./.github/scripts/filter_changed_files.sh "website" "packages/flight-icons/catalog.json"
        
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    needs: [conditional-skip]
    if: needs.conditional-skip.outputs.trigger-ci == 'true'

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Install Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn run lint
        working-directory: website

  test:
    name: 'Test'
    runs-on: ubuntu-latest
    needs: [conditional-skip]
    if: needs.conditional-skip.outputs.trigger-ci == 'true'

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
      - name: Install Node
        uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn
          cache-dependency-path: yarn.lock
      - name: Install Dependencies
        run: yarn install --immutable
      - name: Build Icons
        run: yarn build
        working-directory: packages/ember-flight-icons
      - name: Build Components
        run: yarn build
        working-directory: packages/components
      - name: Run Tests
        run: yarn run test:ember
        working-directory: website
